sudo: false
notifications:
  email:
    - nathan.adamse@bluefinsolutions.com
language: node_js
node_js:
  - '4'
  - '0.12'
  - '0.10'
before_script:
  - npm install -g grunt-cli
matrix:
  fast_finish: true